apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-web-deploy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/65160104/argocdwebtest.git'
    targetRevision: HEAD
    path: /argocd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
