apiVersion: apps/v1
kind: Ingress
metadata:
  name: my-ingress
spec:
  rules:
  - host: myapp.example.com
    http:
      paths:
      - path: 1  /
        backend:
          service:
            name: my-service
            port:
              number: 80